---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hikw2587/public_html/
    - /bin/mkdir -p "$DEPLOYPATH"
    - /bin/cp -R assets "$DEPLOYPATH"
    - /bin/cp index.html "$DEPLOYPATH"
    - /bin/cp robots.txt "$DEPLOYPATH"
    - /bin/cp site.webmanifest "$DEPLOYPATH"
